### ISSUE TITLE
Issue with cloud integration

### ISSUE THREAD

**Issue by ssnirgudkar** [segments-ai/docs#1]
Hello Bert,

First of all, thank you for providing integration with cloud. It's superhelpful. I tried uploading images from my AWS S3 bucket to my segments.ai account and have 2 observations - 

1. If I submit using S3 protocol URI instead of the complete path including the aws region etc, I get the following error. It's somehow linked to the **eu** region rather than the **us** region as it's default setting perhaps? 
2. 
"<Error>
<Code>AuthorizationQueryParametersError</Code>
<Message>Error parsing the X-Amz-Credential parameter; the region **'eu-**west-2' is wrong; expecting 'us-east-2'</Message>
<Region>us-east-2</Region>
<RequestId>JGFW7F8E1BG00VAH</RequestId>
<HostId>U+/LbS0pNCwMVrRwjvr0n85q+qGvBCwaxJDQfyXau6qyE68U0E7LA4NPu6cswjyd5QuGeVsAqdY=</HostId>
</Error>" 

2. So then I gave the full URL path with the aws region name, bucket etc. All bucket and CORS permissions were given as provided in the documentation. It then did upload the image successfully, however I get an access denied error when I try to open it in segments.io. I tried making the bucket public as well as private and keeping the bucket policies and cors permissions. But that doesn't help. Do you know why I get an access denied while opening, but it's able to upload it? is there any additional policy that may be needed on the S3 bucket? Error is below - 
"<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BCXBTDBKVBADFWX3</RequestId>
<HostId>YdaLwhJBT2gpHHKC70dtg2NliRbYT/5QNvA238H0WoW0MWvo/u167oMmg0ST7Hs2T3VEgmBOgoU=</HostId>
</Error>"

**Comment by dbbert** [comment]
Sending you an email for this!
